#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
generate-pmgr-dtsi.py — extract the Apple T8132 (M4) PMGR power-domain tree
from the live Apple Device Tree and emit t8132-pmgr.dtsi for U-Boot/Linux.

This is pure extraction: every node's register offset, label, and parent link
comes from the ADT `devices`/`ps-regs` blobs on real hardware, parsed with the
exact struct layout m1n1 uses (src/pmgr.c, `struct pmgr_device`). Nothing is
invented — re-running it on the machine reproduces the file byte for byte.

The "mechanical but large" bring-up item: Asahi hand-maintains ~1100 lines of
these per SoC; this generates the t8132 equivalent from measured data.

Run on the M4 itself:
    python3 generate-pmgr-dtsi.py > ../patches/t8132-pmgr.dtsi
"""

import re
import struct
import subprocess
import sys

PWRSTATE_COMPAT = '"apple,t8132-pmgr-pwrstate", "apple,pmgr-pwrstate"'
PMGR_FLAG_VIRTUAL = 0x10


def read_adt_pmgr():
    out = subprocess.run(
        ["ioreg", "-lw0", "-p", "IODeviceTree", "-n", "pmgr", "-r", "-d", "1"],
        capture_output=True, text=True).stdout
    dev = bytes.fromhex(re.search(r'"devices" = <([0-9a-f]+)>', out).group(1))
    psr = bytes.fromhex(re.search(r'"ps-regs" = <([0-9a-f]+)>', out).group(1))
    return dev, psr


def parse(dev, psr):
    ps_regs = [struct.unpack_from("<III", psr, i * 12) for i in range(len(psr) // 12)]
    n = len(dev) // 48
    first = [dev[i * 48 + 3] for i in range(min(2, n))]
    u8id = n >= 2 and first[0] != first[1]

    devices = []
    for i in range(n):
        r = dev[i * 48:(i + 1) * 48]
        flags = r[0]
        id1 = r[3]
        if u8id:
            parents = [r[4], r[5]]
        else:
            parents = list(struct.unpack_from("<HH", r, 4))
        addr_offset = r[10]
        psreg_idx = r[11]
        id2 = struct.unpack_from("<H", r, 0x1A)[0]
        name = r[0x20:0x30].split(b"\0")[0].decode("ascii", "replace")
        dev_id = id1 if u8id else id2
        devices.append(dict(flags=flags, id=dev_id, parents=parents,
                            addr_offset=addr_offset, psreg_idx=psreg_idx,
                            name=name))
    return ps_regs, devices, u8id


def label_of(name):
    # Asahi convention: lower-case, keep alnum/underscore, '.' and '-' -> '_'
    return re.sub(r"[^a-z0-9_]", "_", name.lower())


def main():
    dev, psr = read_adt_pmgr()
    ps_regs, devices, u8id = parse(dev, psr)

    id_to_label = {}
    for d in devices:
        if d["id"] and d["id"] not in id_to_label:
            id_to_label[d["id"]] = "ps_" + label_of(d["name"])

    # First pass: which device ids actually get emitted (main reg block,
    # non-virtual)? Parent links may only target these, or dtc fails on a
    # dangling phandle.
    def is_emitted(d):
        pi = d["psreg_idx"]
        return (pi < len(ps_regs) and ps_regs[pi][0] == 0
                and not (d["flags"] & PMGR_FLAG_VIRTUAL))
    emitted_ids = {d["id"] for d in devices if is_emitted(d) and d["id"]}

    emitted = skipped_region = skipped_virtual = 0
    lines = []
    lines.append("// SPDX-License-Identifier: GPL-2.0+ OR MIT")
    lines.append("/*")
    lines.append(" * PMGR power domains for the Apple T8132 \"M4\" SoC")
    lines.append(" *")
    lines.append(" * GENERATED by experimental/t8132-bringup/pmgr/generate-pmgr-dtsi.py")
    lines.append(" * from the live Apple Device Tree of a Mac mini (2024, Mac16,10).")
    lines.append(f" * {len(devices)} ADT pmgr devices; emitting the main register block")
    lines.append(" * (ps-regs reg_idx 0). Offsets and parent links are extracted, not")
    lines.append(" * guessed. See pmgr/README.md.")
    lines.append(" */")
    lines.append("")
    lines.append("&pmgr {")

    for d in devices:
        pi = d["psreg_idx"]
        if pi >= len(ps_regs) or ps_regs[pi][0] != 0:
            skipped_region += 1
            continue
        if d["flags"] & PMGR_FLAG_VIRTUAL:
            skipped_virtual += 1
            continue
        offset = ps_regs[pi][1] + (d["addr_offset"] << 3)
        label = "ps_" + label_of(d["name"])
        parents = [id_to_label[p] for p in d["parents"]
                   if p and p in emitted_ids and id_to_label[p] != label]
        lines.append(f"\t{label}: power-controller@{offset:x} {{")
        lines.append(f"\t\tcompatible = {PWRSTATE_COMPAT};")
        lines.append(f"\t\treg = <0x{offset:x} 4>;")
        lines.append("\t\t#power-domain-cells = <0>;")
        lines.append("\t\t#reset-cells = <0>;")
        lines.append(f'\t\tlabel = "{d["name"].lower()}";')
        if parents:
            refs = ", ".join(f"<&{p}>" for p in parents)
            lines.append(f"\t\tpower-domains = {refs};")
        lines.append("\t};")
        lines.append("")
        emitted += 1

    lines.append("};")
    sys.stderr.write(
        f"emitted {emitted} power domains "
        f"(skipped {skipped_virtual} virtual, {skipped_region} in other reg blocks; "
        f"u8id={u8id})\n")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
