#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""
derive-chickens.py — turn a measured HID/EHID capture (from
trace-donan-chickens.py) into the two MEASURED regions of chickens_donan.c.

Input  : capture file, lines of  "<ecore|pcore> <SYS_IMP_APL_*HIDnn> <hexval>"
Output : either
   --emit-c        a standalone chickens_donan.c body (msr writes), or
   --patch FILE    rewrite the MEASURED-{ECORE,PCORE} regions of an existing
                   chickens_donan.c in place.

The generated writes are plain `msr(reg, value)` of the exact values the real
firmware used — no interpretation, no masking heuristics. That keeps the
transform honest: it reproduces measured behaviour rather than inventing it.
A reviewer can diff the generated values against the capture line-for-line.
"""

import argparse
import re
import sys

ECORE_BEGIN = "/* >>> MEASURED-ECORE-BEGIN"
ECORE_END = "/* <<< MEASURED-ECORE-END */"
PCORE_BEGIN = "/* >>> MEASURED-PCORE-BEGIN"
PCORE_END = "/* <<< MEASURED-PCORE-END */"

REG_RE = re.compile(r"^(ecore|pcore)\s+(SYS_IMP_APL_E?HID\d+)\s+(0x[0-9a-fA-F]+)\s*$")


def parse_capture(path):
    ecore, pcore = [], []
    with open(path) as f:
        for ln in f:
            ln = ln.strip()
            if not ln or ln.startswith("#"):
                continue
            m = REG_RE.match(ln)
            if not m:
                print(f"warning: skipping unparseable line: {ln!r}", file=sys.stderr)
                continue
            ctype, reg, val = m.group(1), m.group(2), int(m.group(3), 16)
            (ecore if ctype == "ecore" else pcore).append((reg, val))
    # de-duplicate, last write wins (matches hardware semantics)
    def dedup(pairs):
        seen = {}
        for reg, val in pairs:
            seen[reg] = val
        return sorted(seen.items())
    return dedup(ecore), dedup(pcore)


def emit_writes(pairs, indent="    "):
    if not pairs:
        return f"{indent}/* (capture contained no writes for this core type) */"
    return "\n".join(f"{indent}msr({reg}, 0x{val:016x}UL);" for reg, val in pairs)


def render_region(pairs, kind):
    body = emit_writes(pairs)
    return (f"    /* >>> MEASURED-{kind}-BEGIN (populated by derive-chickens.py) */\n"
            f"{body}\n"
            f"    /* <<< MEASURED-{kind}-END */")


def splice(source, begin_marker, end_marker, replacement):
    start = source.index(begin_marker)
    # back up to the start of the indented marker line
    line_start = source.rfind("\n", 0, start) + 1
    end = source.index(end_marker) + len(end_marker)
    return source[:line_start] + replacement + source[end:]


STANDALONE_TEMPLATE = """\
/* SPDX-License-Identifier: MIT */
/* GENERATED by derive-chickens.py from a measured HID/EHID capture.
 * Do not edit by hand; re-run the trace + generator instead. */
#include "cpu_regs.h"
#include "utils.h"

void init_t8132_donan_ecore(int rev)
{{
    UNUSED(rev);
{ecore}
}}

void init_t8132_donan_pcore(int rev)
{{
    UNUSED(rev);
{pcore}
}}
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("capture", help="capture file from trace-donan-chickens.py")
    ap.add_argument("--patch", metavar="CHICKENS_DONAN_C",
                    help="rewrite MEASURED regions of this file in place")
    ap.add_argument("--emit-c", action="store_true",
                    help="print a standalone chickens_donan.c to stdout")
    args = ap.parse_args()

    ecore, pcore = parse_capture(args.capture)
    sys.stderr.write(f"parsed {len(ecore)} E-core + {len(pcore)} P-core register writes\n")

    if args.patch:
        with open(args.patch) as f:
            src = f.read()
        src = splice(src, ECORE_BEGIN, ECORE_END, render_region(ecore, "ECORE"))
        src = splice(src, PCORE_BEGIN, PCORE_END, render_region(pcore, "PCORE"))
        with open(args.patch, "w") as f:
            f.write(src)
        sys.stderr.write(f"rewrote MEASURED regions in {args.patch}\n")
        return 0

    # default / --emit-c
    print(STANDALONE_TEMPLATE.format(
        ecore=emit_writes(ecore),
        pcore=emit_writes(pcore),
    ))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
